# -*- coding: utf-8 -*-
"""catch the ghost.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1D4bo4lX7oVkImgoSOlNKq9xBfIlP40hX
"""

! pip install imagehash pillow

import os
import json
import imagehash
from PIL import Image
import smtplib
from email.mime.text import MIMEText

DB_FILE = 'database.json'
PHOTO_FOLDER = '/content/'

def load_database():
    if not os.path.exists(DB_FILE):
        return []
    with open(DB_FILE, 'r') as f:
        return json.load(f)

def save_database(data):
    with open(DB_FILE, 'w') as f:
        json.dump(data, f, indent=2)

def get_image_hash(image_path):
    with Image.open(image_path) as img:
        return str(imagehash.phash(img))

def find_duplicates(database, new_entry):
    dupes_same_order = []
    dupes_cross_order = []
    for entry in database:
        if entry['hash'] == new_entry['hash']:
            if entry['order_id'] == new_entry['order_id']:
                dupes_same_order.append(entry)
            else:
                dupes_cross_order.append(entry)
    return dupes_same_order, dupes_cross_order

def send_email(subject, body):
    msg = MIMEText(body)
    msg['Subject'] = subject
    msg['From'] = 'at46418@gmail.com'
    msg['To'] = 'at46418@gmail.com'

    # Example: Print instead of send
    print("\n--- EMAIL ALERT ---")
    print(f"Subject: {subject}")
    print(body)
    print("-------------------\n")

def scan_folder():
    database = load_database()
    for filename in os.listdir(PHOTO_FOLDER):
        if filename.endswith(('.jpg', '.png', '.jpeg')):
            order_id, photo_id = filename.split('.')[0].split('_')
            image_path = os.path.join(PHOTO_FOLDER, filename)
            image_hash = get_image_hash(image_path)

            new_entry = {
                "order_id": order_id,
                "photo_id": photo_id,
                "hash": image_hash
            }

            dupes_same, dupes_cross = find_duplicates(database, new_entry)

            if dupes_same:
                photo_ids = [d['photo_id'] for d in dupes_same] + [photo_id]
                body = f"Duplicate detected **within** order {order_id}.\nPhoto IDs: {photo_ids}"
                send_email(f"Duplicate in Order {order_id}", body)

            if dupes_cross:
                order_ids = list({d['order_id'] for d in dupes_cross} | {order_id})
                body = f"Duplicate detected **across** orders.\nOrders: {order_ids}\nMatching Photo ID: {photo_id}"
                send_email(f"Cross-order Duplicate Found", body)

            # Save new entry to database
            database.append(new_entry)

    save_database(database)

if __name__ == '__main__':
    scan_folder()

"""# Test Section"""

import os
import shutil
import json
from PIL import Image
#from catch_ghosts import get_image_hash, find_duplicates, load_database, save_database

def setup_test_photos():

    shutil.copyfile('/content/img_01.jpg', '/content/img_04.jpg')

def test_get_image_hash():
    hash1 = get_image_hash('/content/img_01.jpg')
    hash2 = get_image_hash('/content/img_04.jpg')
    print(f"Hash1: {hash1}, Hash2: {hash2}")
    assert hash1 == hash2, "Hashes should match for duplicate images"

def test_find_duplicates():
    dummy_db = [
        {"order_id": "1001", "photo_id": "001", "hash": "abc123"},
        {"order_id": "1001", "photo_id": "002", "hash": "xyz999"},
        {"order_id": "1002", "photo_id": "001", "hash": "abc123"},
    ]

    new_entry_same_order = {"order_id": "1001", "photo_id": "003", "hash": "abc123"}
    same_order, cross_order = find_duplicates(dummy_db, new_entry_same_order)
    print(cross_order)
    #print(same_order)
    assert len(same_order) == 1, "Expected 1 duplicate in the same order"
    assert same_order[0]['photo_id'] == '001'
    #assert len(cross_order) == 1, "Expected no cross-order duplicate"
    #assert len(cross_order) == 0, f"Expected no cross-order duplicates, but got {len(cross_order)}"
    if len(cross_order) == 0:
        print(" No cross-order duplicates found (as expected)")
    else:
        print(f"Unexpected cross-order duplicates found: {cross_order}")


    new_entry_cross_order = {"order_id": "1003", "photo_id": "004", "hash": "abc123"}
    same_order2, cross_order2 = find_duplicates(dummy_db, new_entry_cross_order)
    print(cross_order2)
    print(same_order2)
    assert len(same_order2) == 0
    assert len(cross_order2) == 2, "Expected 2 cross-order duplicates"

def test_db_read_write():
    dummy_data = [{"order_id": "x", "photo_id": "1", "hash": "zzz"}]
    save_database(dummy_data)
    loaded = load_database()
    assert loaded == dummy_data, "Database read/write mismatch"

if __name__ == "__main__":
    print("Running tests...\n")
    setup_test_photos()
    test_get_image_hash()
    test_find_duplicates()
    test_db_read_write()
    print("\n✅ All tests passed.")

